language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: P6TJAh64bJHH7pzrRutRSYbIZGZ0/AAW4C9h4D+XsPvTuF7Z5xIP4S3idkUh3oe+a0Y2GFE+/fCvEKYBHh185o/fscAYwWtY/rSpmwHfovB8GWRBLPteNeJDZcOQgV0M6SRXdcjFPW7NHOrhJp/Oekr6kz8JRGoE74SNuWcH9rL2XeqNLmARarTR5dfX0EISpPZHHN3pXD9xAfGmMebYqXLQb1ym4R0i2ecppnFDF7hnC28A0a2Jz4XA2mILQ3653UZkUug9UZf11zxrkAjxf+/Mv9Q3bsKDMVw69nFUJPRfBqM++Vsi3O0JmkTHlTBJsMHZ3eiFPdOJvuioKe6FxHvq9J3vLHUynFO2FSXLG+xWnkKSr7ZOohj/MyLUHk/y/OcY0mkiP6+Gq8O26CBhaKo+urPo4Qt0aJg4fcyuD/FNvbRk2ADQHNRJlC3OqMjX3w2rBUuPDBSAsaBzNwcaKsDkVZLAic9lc4j19rlnA9PWYfcsTQQ8/AJTzq4LXkaQtB+PfoVhUGeNjsr3uv6mLjufLVTNEfqjJG+C60QS6ZQ0oMiwB2aDt05MXqbj2wl3S+s8J/oIe+1xaCG5APGL+fatzHsBNh7FM54/tWblfP4LrbqymdowtL2v+rZ6fp0l1idqQbldE0ou/CX1hej9Gjoyp2QTwLAMkeEf9mUd334=
  - secure: S0ZacA6N3cdvyVdLSYj/QhZLFFplbS/A/sj9IpVQIXa9WpxB4WXDo/5UKYztfnYnQieJAhJxsBhEzVveFpKHm/FmwP4R6Oo+VsfbNyLqipv25fBM6uuIBOycVDZJxkZdXGEQ33nyH6clni7ugzhGbcX0LJY8N5fepnGKDNXt/EKw6RdCrZtSdnmP6kW6Hnmf+3S+7/9cIHbCdEYieXE9/mJ1X8mGxN54J4ixZH7aTkCx/2TCSLqrizdiRVTDUzrdZXux01WQT6+THkXS0dTiz7229Z7ElBLlp/wMyPl2/9/tLKPQiynyqp5ENLUMt5QPrmHIH59CXPYw7ufRXbUU/zg4SvNP3rvep+dOqNszdzCmPB9gSqLTHZKx2K4wHV70eZBt3DyY6PmLTegT7z5eFDYtIxCJ8BKERsqmF+7LX8kW/BWwBO3kX4h/5eT+obr815DMq2uSOl8AEOp5h5C9VSlNsmTneqCd2KS7SV/BMXENQnjqwuADlXg00J5ekowTA+ZTw7V7C3HvEvABSVfBnX3bEj5hAjHyNgYrL+rWRx1Mu4PMohyA/x6wZ4fRAZXZDMvr2Q22nAyaC3gMQcXwXtjOc4RhKRgAuAKFVvKiA7kJgImUoGkRtWU5XXvAmv8suX2DxDohWFZ3DcOeesypoAadOHRB6SQxOzK+diQa8gw=
