language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:  
  global:
  - secure: Y6Ct3xApBTkIUFYewzFDmoBaH5jJ2C8nWqpl4IW8tAQg7UgvqlCERg7TW8a1yOa9R4bEJ7JoUeX4CMQfcPmRq7qEt5bXBTjWbU2pK3IY8ad/K3BQkuTgcMP4ZhVrWfMCtXmzmjAhwpfYNDlgFFDkHCgC4/2wWjAyEoYvtNjsNQZudtCBT9cMimVAvei6prvfCdFzZJk6tETQglAzsU+BGHV2iqsXHC9NSO1MBPoxVFrvkHtGe9wol8Lws2R9uI25I8YaxuK3vDd1ElZOeywRLLSxgjcvyBEI/2X33rEiIe+RkDQlKeMxCWV6fNzY2ffY+umDBEd7GHGJKQUAfJmosUB48BVgjUO+KBnNDO+/0DmjzGWpKggJeXSqFpfNZblDhsXs6dRiyj/aTVqeyMW5tFBDl9MZ8hax6KugLqYlbGy2NjO/9h/g0+1Q53JfPdRg8nL8ZCZrT+BFNQQUlC0VzGkWlQM3WAT0IM7e9B5mEXCynrSxpxxgPleI7R8yWiNuUYxEvWcrty4PvdPLC/0j4eRKgL+UtLVURjyOyRvJgtHKhYggcsteeKqDEkaMFPcJdM0Yy3QqHgjJKj+FgAINNkZF9KRJ5+qHjI5qbC8oYAOaniLFYnjfSd4DDXcWG4LHTkTgXrQTjZor0aOl6/JdLfYW4TGoy0p9WTNZIFbZADo=
  - secure: P2C9tfLbY0YrhsNoQn34CJIes0UB42ktnH9p7hCPoA5tOlRBqzsYxg4+AMTgJI52+g9qRu7TVFneZvrDFP0u5Jiwzty4AkpM+UedXnszqIeY0c82mPog1jQYfCAvsGlAnEOw4rFLyrMxgvqCXB9uNpTdxzIGmtb5jnJiLiIPz4iZIk4PvF2yEtFKMyg4jnAKcdyOe7bSJ4nvA/b817Yn8irr4ofQe/ZJiQq27dyQX2zU9+e0v1WKRLEi9a+lKNN742NydM+7gmE9EdvYD5eJFISQfjSPlFI64jEJMV4XxSmPHjt6VTkY6kvV+gzUvHYa+uhCGHzIclRabqPydaIm1QQqeUzmHiCyeWwQ5xsgYHGjhWFN18PIl4Owxv0YMyGbTH53u3Gjrjq3o5sqfKcq9Me4kYMmYYXr4aMv4jtXXFmklL1sZ6zS9JUWMVNKgzQaM2GEEtjAMAW7E75tm1IGOSNQXrJXW+G9ZGheDnoWTwq4sO+pIaoGkJGkKEz6TecQYKwV5hAwNJgLi3SyUfiLSJimGHXn7MCbauop1nJxuf5Yuylqi9LPH352nZitV+eY8TxpjEKo1HzL+LpsJSNg+HMlFg+mgFyvecSH3sA0xeMzckDVIO5Mx2B3d8wRTlhXpV7E8uWNJqbEfbHEHWiwif+7Tc+Xz+4iNnLP6wTeyZ4=